/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String args[]) {
		
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
